#!/bin/bash


cd ~
git clone https://aur.archlinux.org/yay.git yay && cd yay && makepkg -si

sudo pacman -S discord flameshot ranger fzf htop kitty zsh \
    zathura zathura-pdf-poppler fd ripgrep xclip
